### ISSUE TITLE
Add links to documentation in chart config files

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#533]
add URLs in the YAML and then display them in the shiny app page for each chart.

**Comment by jwildfire** [comment]
I'm thinking we'll just allow a links item in the chart YAML files, where one or more named links can be provided. These will then be added in a (collapsable?) header section whenever the chart is shown. For example, we might add the following to the YAML for hepexplorer: 

``` 
label: Hepatic Safety Explorer
type: htmlwidget
domain: labs
package: safetyCharts  
export: true
workflow:
  widget: hepexplorer
links:
  homepage: https://github.com/SafetyGraphics/hep-explorer
  wiki: https://github.com/SafetyGraphics/hep-explorer/wiki 
  issues: https://github.com/SafetyGraphics/hep-explorer/issues
  demo: https://safetygraphics.github.io/hep-explorer/test-page/example1/
```
