### ISSUE TITLE
Allow a `parent` chart configuration

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyGraphics#640]
Goal is to minimize duplication in chart configuration files. For example, many charts from the labs domain can easily be reused with ECG/QT and vital sign data. See https://github.com/SafetyGraphics/safetyCharts/pull/90 for a nice demo of how this might work. 

The PR above has significant duplicative code between the chart configuration files. For example, the safetyOutlierExplorer YAML config (for lab data) looks like this: 

```
env: safetyGraphics
label: Outlier Explorer
type: htmlwidget
package: safetyCharts
export: true
domain: 
  - labs
workflow:
  init: init_safetyOutlierExplorer
  widget: safetyOutlierExplorer
links:
  Homepage: https://github.com/RhoInc/safety-outlier-explorer
  Wiki: https://github.com/RhoInc/safety-outlier-explorer/wiki 
  Issues: https://github.com/RhoInc/safety-outlier-explorer/issues
  Demo: https://rhoinc.github.io/safety-outlier-explorer/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
```

This config is [largely duplicated for QT](https://github.com/SafetyGraphics/safetyCharts/blob/81-qt-prototype/inst/config/QTsafetyOutlierExplorer.yaml). The only needed changes are in `label`, `domain` and (possibly) `workflow`. To avoid this duplication, we could develop a process to re-use `configuration` files across multiple studies. 

One option might be to add support for a `parent` parameter in the chart config. This would allow a different chart config to be used as a template. Other parameters in the config would overwrite values found in the template. For the example above, this would lead to a simplified config that looks like this:

```
parent: safetyOutlierExplorer
label: QT Outlier Explorer
domain: 
  - ecg
```

To implement we'd to add a method in `makeChartConfig` that would handle the merge.
